spring.application.name=administrativo

spring.datasource.url=jdbc:postgresql://localhost:5432/javify-db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.profiles.active=demo

